spring:
  application:
    name: Student-Attendance


  profiles:
    active: dev

  datasource:
    url: enter your db URL
    username: enter your db user name
    password: enter your db password



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081

logging:
  file:
    name: logs/spring.log
  level:
    root: INFO
    com.AS.Student_Attendance: INFO